### ISSUE TITLE
master missing catta update

### ISSUE THREAD

**Issue by tomberek** [meshlink/meshlink#68]
seems like catta ref 08ac450b42b7533e97c02c02bbbef8946b9582fb is not uploaded to github. The system still seems to work with catta master (f1de9dcaab953757252d51b4725cbfa36daa10a5).

**Comment by gsliepen** [comment]
That catta ref is uploaded to GitHub: https://github.com/meshlink/catta/commit/08ac450b42b7533e97c02c02bbbef8946b9582fb

**Comment by tomberek** [comment]
Yes, the submodule in meshlink refers to the origin as https://github.com/catta-x/catta 
Contents of .gitmodules in everbase:
```
[submodule "catta"]
        path = catta
        url = git@github.com:catta-x/catta.git
        branch = develop
[submodule "src/utcp"]
        path = src/utcp
        url = git@github.com:meshlink/utcp.git
        branch = master
```
In master:
```
[submodule "catta"]
        path = catta
        url = git://meshlink.io/catta
        branch = develop
[submodule "src/utcp"]
        path = src/utcp
        url = git://meshlink.io/utcp
```
It's possible to get it working, but can get confusing for people not familiar with submodules. Having the submodules refer to meshlink.io may cause a similar disconnect where a ref exists at meshlink, but not on github.

Otherwise, i like the library, thanks! I'm exploring it for use in a distributed system. I've build a Nix expression for it and catta so i can add it to https://github.com/NixOS/nixpkgs if that's okay with you.

**Comment by gsliepen** [comment]
Ah I see. I'll see if I can turn the submodule URLs into relative ones, so they work whether you checked out a copy from meshlink.io or github.com.

It's fine to package the code for NixOS! MeshLink is GPL2, and Catta is LGPL2.1.

**Comment by gsliepen** [comment]
Changed .gitmodules to use relative URLs in commit a4de87c. Thanks for reporting the issue!
